apiVersion: apps/v1
kind: Deployment
metadata:
  name: freebilly
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: freebilly
  template:
    metadata:
      labels:
        app: freebilly
    spec:
      containers:
      # modify the following line with your Docker Hub account name
      - image: index.docker.io/emileten/freebilly:0.1.0
        name: freebilly
        ports:
        - containerPort: 8080
  restartPolicy: Never 
