apiVersion: apps/v1
kind: Deployment
metadata:
  name: freebilly
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: freebilly
  template:
    metadata:
      labels:
        app: freebilly
    spec:
      containers:
        - image: ubuntu
          name: ubuntu
          command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
          ports:
          - containerPort: 8080
      # - image: index.docker.io/emileten/freebilly:0.1.0
      #   name: freebilly
      #   ports:
      #   - containerPort: 8080