apiVersion: apps/v1
kind: Deployment
metadata:
  name: freebilly
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: freebilly
  template:
    metadata:
      labels:
        app: freebilly
    spec:
      containers:
      - image: index.docker.io/emileten/freebilly:dev
        name: freebilly
        command: ["freebilly"]
        args: ["--help"]
        ports:
        - containerPort: 8080